const $=id=>document.getElementById(id),sample=[{t:0,d:150},{t:.5,d:95},{t:1,d:55},{t:1.5,d:92},{t:2,d:160}];
const state={source:'sample',old:null,newer:null,versions:JSON.parse(localStorage.getItem('tunerVersions')||'[]')};
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function rows(){return [...document.querySelectorAll('#dataRows tr')].map(tr=>({t:+tr.querySelector('.time').value,d:+tr.querySelector('.distance').value})).filter(x=>Number.isFinite(x.t)&&Number.isFinite(x.d)).sort((a,b)=>a.t-b.t)}
function addRow(t='',d=''){let tr=document.createElement('tr');tr.innerHTML=`<td><input class="time" type="number" step="0.1" value="${esc(t)}"></td><td><input class="distance" type="number" value="${esc(d)}"></td><td><button class="remove">×</button></td>`;tr.querySelector('.remove').onclick=()=>{tr.remove();draw(rows())};tr.querySelectorAll('input').forEach(i=>i.oninput=()=>{source('real','手动记录');draw(rows())});$('dataRows').append(tr)}
function source(kind,label){state.source=kind;$('sourceBadge').className='source '+kind;$('sourceBadge').textContent=label;$('status').textContent=kind==='sample'?'正在使用示例':'已获得真实记录'}
function load(data,kind='sample',label='示例数据'){$('dataRows').innerHTML='';data.forEach(x=>addRow(x.t,x.d));source(kind,label);reset();draw(data)}
function reset(){state.old=state.newer=null;$('oldResult').textContent='等待测试';$('newResult').textContent='尚未生成';$('resultState').textContent='尚未回放';$('resultState').className='pill neutral';$('apply').disabled=true;$('accept').disabled=true;['oldFalse','newFalse','oldMiss','newMiss','oldResponse','newResponse'].forEach(id=>$(id).textContent='--')}
function evaluate(data,threshold,hold){let start=null,triggered=false,triggerAt=null;for(const p of data){if(p.d<threshold){if(start===null)start=p.t;if(p.t-start>=hold&&!triggered){triggered=true;triggerAt=p.t}}else start=null}return{triggered,triggerAt}}
const expectedOn=()=>!$('expectedText').value.includes('不')&&!$('expectedText').value.includes('关闭');
function draw(data,oldEval,newEval){if(!data.length){$('chart').innerHTML='<div class="chart-empty">请至少录入一行数据</div>';return}let maxT=Math.max(...data.map(x=>x.t),1),maxD=Math.max(...data.map(x=>x.d),200),points=data.map(x=>`${x.t/maxT*100},${88-x.d/maxD*72}`).join(' ');$('chart').innerHTML=`<div class="axis-label">距离 cm</div><svg viewBox="0 0 100 100" preserveAspectRatio="none"><line x1="0" y1="${88-(+$('distance').value/maxD)*72}" x2="100" y2="${88-(+$('distance').value/maxD)*72}" class="threshold-line"/><polyline points="${points}"/>${data.map(x=>`<circle cx="${x.t/maxT*100}" cy="${88-x.d/maxD*72}" r="1.8"/>`).join('')}</svg><div class="time-label">0 — ${maxT}s</div><div class="chart-legend"><span>动作距离</span><span class="threshold-key">触发距离</span></div>${oldEval?`<div class="playback old-play" style="left:${Math.min(92,(oldEval.triggerAt??maxT)/maxT*100)}%">旧：${oldEval.triggered?'亮':'不亮'}</div>`:''}${newEval?`<div class="playback new-play" style="left:${Math.min(92,(newEval.triggerAt??maxT)/maxT*100)}%">新：${newEval.triggered?'亮':'不亮'}</div>`:''}`}
function updateRule(){let h=+$('duration').value;$('oldRule').textContent=`当前规则：距离小于 ${$('distance').value} cm，${h?`持续 ${h} 秒后亮灯`:'立即亮灯'}`;reset();draw(rows())}
$('loadSample').onclick=()=>load(sample);$('addRow').onclick=()=>{addRow();source('real','手动记录')};$('distance').oninput=updateRule;$('duration').oninput=updateRule;
$('csvFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{let data=r.result.trim().split(/\r?\n/).map(x=>x.split(',').map(Number)).filter(x=>x.length>=2&&x.every(Number.isFinite)).map(([t,d])=>({t,d}));data.length?load(data,'real','真实记录 · CSV'):alert('没有读到有效数据。请使用两列格式：时间,距离')};r.readAsText(f)};
$('runOld').onclick=()=>{let data=rows();if(data.length<2){alert('请至少提供两个记录点');return}let threshold=+$('distance').value,hold=+$('duration').value;state.old=evaluate(data,threshold,hold);let mismatch=state.old.triggered!==expectedOn();$('oldResult').textContent=state.old.triggered?'灯亮了':'灯没有亮';$('oldDetail').textContent=`距离 < ${threshold} cm${hold?` 持续 ${hold}s`:'，立即触发'}`;$('resultState').textContent=mismatch?'发现一次错误':'结果符合标注';$('resultState').className='pill '+(mismatch?'bad':'good');if(mismatch&&!expectedOn()&&state.old.triggered){$('diagnosis').innerHTML=`<b>Agent 诊断：</b>“${esc($('actionLabel').value)}”最低到 ${Math.min(...data.map(x=>x.d))} cm，但只短暂接近。只看距离会把经过误判成使用。建议增加 <b>持续 2 秒</b> 的条件。`;$('newResult').textContent='建议：持续 2 秒再亮';$('newDetail').textContent='等待应用并重放';$('apply').disabled=false}else{$('diagnosis').textContent='这条记录没有暴露错误。请继续加入更多真实动作记录，再判断是否需要修改。'}$('accept').disabled=false;draw(data,state.old)};
$('apply').onclick=()=>{let data=rows(),threshold=+$('distance').value;$('duration').value=2;state.newer=evaluate(data,threshold,2);let mismatch=state.newer.triggered!==expectedOn();$('newResult').textContent=state.newer.triggered?'灯亮了':'灯保持关闭';$('newDetail').textContent=`同一记录：距离 < ${threshold} cm 持续 2s`;$('resultState').textContent=mismatch?'仍需调整':'误触发已消除';$('resultState').className='pill '+(mismatch?'bad':'good');$('diagnosis').innerHTML='<b>对比结论：</b>没有更换数据，只更换了规则。旧规则在 55 cm 时误亮；新规则发现接近时间不足 2 秒，因此不亮。';$('oldRule').textContent=`当前候选：距离小于 ${threshold} cm，持续 2 秒后亮灯`;$('oldFalse').textContent=state.old.triggered&&!expectedOn()?'1 次':'0 次';$('newFalse').textContent=state.newer.triggered&&!expectedOn()?'1 次':'0 次';$('oldMiss').textContent=expectedOn()&&!state.old.triggered?'1 次':'0 次';$('newMiss').textContent=expectedOn()&&!state.newer.triggered?'1 次':'0 次';$('oldResponse').textContent=state.old.triggered?`${state.old.triggerAt.toFixed(1)}s`:'—';$('newResponse').textContent=state.newer.triggered?`${state.newer.triggerAt.toFixed(1)}s`:'—';draw(data,state.old,state.newer);$('accept').disabled=false;$('apply').disabled=true};
$('accept').onclick=()=>{let v={name:$('projectName').value,label:$('actionLabel').value,source:$('sourceBadge').textContent,threshold:$('distance').value,hold:$('duration').value,time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})};state.versions.unshift(v);state.versions=state.versions.slice(0,8);localStorage.setItem('tunerVersions',JSON.stringify(state.versions));renderVersions();$('status').textContent='已由人确认'};
function renderVersions(){let rail=$('versionRail');rail.innerHTML=state.versions.length?'':'<div class="rail-empty">完成一次对比后，这里会保存版本</div>';state.versions.forEach((v,i)=>{let b=document.createElement('button');b.className='rail-version';b.innerHTML=`<small>V${state.versions.length-i} · ${esc(v.time)}</small><b>${esc(v.name)}</b><span>${esc(v.label)} · ${esc(v.source)}</span>`;b.onclick=()=>{$('projectName').value=v.name;$('distance').value=v.threshold;$('duration').value=v.hold;$('status').textContent=`已载入 V${state.versions.length-i}`;$('oldRule').textContent=`版本规则：距离小于 ${v.threshold} cm，持续 ${v.hold} 秒后亮灯`};rail.append(b)})}
$('saveProject').onclick=()=>{localStorage.setItem('tunerProject',JSON.stringify({name:$('projectName').value,sensor:$('sensorName').value}));$('status').textContent='项目模板已保存'};let saved=JSON.parse(localStorage.getItem('tunerProject')||'null');if(saved){$('projectName').value=saved.name;$('sensorName').value=saved.sensor}renderVersions();load(sample);
