const $=id=>document.getElementById(id);const state={mode:'natural',runs:0,suggestion:null};
const profiles={natural:{distance:120,enter:.8,fade:1.8,exit:2},sensitive:{distance:160,enter:.3,fade:1.2,exit:1.2},restrained:{distance:90,enter:1.2,fade:2.5,exit:3}};
['distance','enter','fade','exit'].forEach(id=>$(id).addEventListener('input',()=>{$(id+'Out').textContent=$(id).value}));
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode;Object.entries(profiles[state.mode]).forEach(([k,v])=>{$(k).value=v;$(k+'Out').textContent=v})});
function evaluate(){const d=+$('distance').value,e=+$('enter').value,f=+$('fade').value,x=+$('exit').value;const falseTriggers=d>145?2: d<100?0:1;const response=(e+f).toFixed(1);const leave=x.toFixed(1);let text=falseTriggers?'门外路过轨迹触发偏多：建议缩短触发距离，保留当前渐亮速度。':'三组轨迹均通过。当前参数让灯光有明确反馈，也没有明显误触发。';if(falseTriggers){state.suggestion={distance:Math.max(90,d-25),enter:e,fade:f,exit:x}}else{state.suggestion=null}return{falseTriggers,response,leave,text}}
function animate(){const p=$('person');p.style.left='5%';$('lamp').style.background='#e8f0f6';setTimeout(()=>{p.style.left='75%';$('lamp').style.background='rgba(255,210,80,.75)';$('lamp').style.boxShadow='0 0 45px rgba(255,197,58,.55),0 0 0 12px #f3f7fa'},700);setTimeout(()=>{$('lamp').style.background='#e8f0f6';$('lamp').style.boxShadow='0 0 0 12px #f3f7fa'},2600)}
$('run').onclick=()=>{const r=evaluate();state.runs++;$('status').textContent='测试完成';$('scenario').textContent='已完成：正常靠近 · 门外路过 · 快速折返';$('response').textContent=r.response+' s';$('false').textContent=r.falseTriggers+' 次';$('leave').textContent=r.leave+' s';$('diagnosis').textContent='Agent 诊断：'+r.text;$('apply').disabled=!state.suggestion;$('accept').disabled=false;animate();if(state.suggestion)$('diagnosis').textContent+=' 点击“应用 Agent 建议”可复测。';};
$('apply').onclick=()=>{if(!state.suggestion)return;Object.entries(state.suggestion).forEach(([k,v])=>{$(k).value=v;$(k+'Out').textContent=v});$('diagnosis').textContent='已应用建议：触发距离调整为 '+state.suggestion.distance+' cm，准备重新测试。';$('apply').disabled=true;setTimeout(()=>$('run').click(),450)};
$('accept').onclick=()=>{const v=document.createElement('span');v.textContent='V'+state.runs+' · '+new Date().toLocaleTimeString().slice(0,5)+' · '+state.mode;$('versions').prepend(v);$('status').textContent='已确认';$('diagnosis').textContent='用户确认完成，当前参数作为可用版本保存。';};
